version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./config.json:/steve-ai-bot/config.json  # Mount config.json from host to container
    restart: always  # Ensure the container restarts on failure
